<?php
namespace tests;

use PHPUnit\Framework\TestCase as BaseTestCase;


class TestCase extends BaseTestCase{
  protected function setUp():void {
    parent::setUp(); // TODO: Change the autogenerated stub
  }
  protected static  function generator(){
    return $generator = (function (){foreach (['a', 'b', 'c'] as $item) {yield $item;}})();
  }
}